#ifndef __USER_CONFIG_H__
#define __USER_CONFIG_H__

#define USE_WIFI_MODE		STATIONAP_MODE
#define WIFI_CLIENTSSID		"MYSSID"
#define WIFI_CLIENTPASSWORD	"MYPASSWD"
#define WIFI_AP_NAME		"ESP8266"
#define WIFI_AP_PASSWORD	"00000000"
#define PLATFORM_DEBUG		true

#endif
